class Dynamic_Roles {
	#include "Config_Officer.hpp"

	#include "Config_Rifleman.hpp"
	#include "Config_Machinegunner.hpp"
	#include "Config_Medic.hpp"
	#include "Config_Engineer.hpp"
	#include "Config_TeamLeader.hpp"
	#include "Config_SquadLeader.hpp"

	#include "Config_EOD.hpp"
	#include "Config_Diver.hpp"
	#include "Config_Sniper.hpp"
	#include "Config_Spotter.hpp"
	#include "Config_Paratrooper.hpp"

	#include "Config_Pilot.hpp"
	#include "Config_UAVOp.hpp"

	#include "Config_Crewman.hpp"
};

class Common_Arsenal {
	weapons[] = {
		"arifle_Katiba_F",
		"arifle_Katiba_C_F",
		"arifle_Katiba_C_F",
		"arifle_Katiba_C_F",
		"arifle_CTAR_blk_F",
		"arifle_CTAR_hex_F",
		"arifle_ARX_blk_F",
		"arifle_ARX_hex_F",
		"launch_RPG32_F",
		"launch_RPG32_tan_lxWS",
		"launch_O_Titan_short_F",
		"launch_PSRL1_sand_RF",
		"launch_PSRL1_PWS_sand_RF",
		"launch_O_Vorona_brown_F",
		"launch_O_Titan_F"
	};
	magazines[] = {
		"30Rnd_65x39_caseless_green",
		"30Rnd_65x39_caseless_green_mag_Tracer",
		"ACE_30Rnd_65x39_caseless_green_mag_Tracer_Dim",
		"30Rnd_580x42_Mag_F",
		"30Rnd_580x42_Mag_Tracer_F",
		"30Rnd_65x39_caseless_green",
		"30Rnd_65x39_caseless_green_mag_Tracer",
		"ACE_30Rnd_65x39_caseless_green_mag_Tracer_Dim",
		"10Rnd_50BW_Mag_F",
		"150Rnd_762x54_Box",
		"150Rnd_762x54_Box_Tracer",
		"150Rnd_762x51_Box",
		"150Rnd_762x51_Box_Tracer",
		"150Rnd_93x64_Mag",
		"1Rnd_Pellet_Grenade_shell_lxWS",
		"1Rnd_HE_Grenade_shell",
		"UGL_FlareGreen_F",
		"UGL_FlareCIR_F",
		"UGL_FlareRed_F",
		"UGL_FlareWhite_F",
		"UGL_FlareYellow_F",
		"UGL_FlareGreen_Illumination_F",
		"UGL_FlareRed_Illumination_F",
		"UGL_FlareWhite_Illumination_F",
		"UGL_FlareYellow_Illumination_F",
		"1Rnd_SmokeBlue_Grenade_shell",
		"1Rnd_SmokeGreen_Grenade_shell",
		"1Rnd_SmokeOrange_Grenade_shell",
		"1Rnd_SmokePurple_Grenade_shell",
		"1Rnd_SmokeRed_Grenade_shell",
		"1Rnd_Smoke_Grenade_shell",
		"1Rnd_SmokeYellow_Grenade_shell",
		"RPG32_HE_F",
		"RPG32_F",
		"Titan_AA",
		"Titan_AP",
		"Titan_AT",
		"PSRL1_AT_RF",
		"PSRL1_FRAG_RF",
		"PSRL1_HE_RF",
		"PSRL1_HEAT_RF",
		"Vorona_HE",
		"Vorona_HEAT",
		"ACE_Chemlight_HiBlue",
		"ACE_Chemlight_HiGreen",
		"ACE_Chemlight_HiRed",
		"ACE_Chemlight_HiWhite",
		"ACE_Chemlight_HiYellow",
		"ACE_Chemlight_IR",
		"ACE_HandFlare_Green",
		"ACE_HandFlare_Red",
		"ACE_HandFlare_White",
		"ACE_HandFlare_Yellow",
		"ACE_CTS9",
		"ACE_M84",
		"APERSMineDispenser_Mag",
		"ClaymoreDirectionalMine_Remote_Mag",
		"ATMine_Range_Mag",
		"APERSBoundingMine_Range_Mag",
		"ACE_HuntIR_monitor",
		"ACE_RangeTable_82mm",
		"ACE_artilleryTable",
		"acex_intelitems_notepad",
		"ACE_SpareBarrel",
		"ACRE_PRC343",
		"ACE_CableTie",
		"ACE_Chemlight_Shield",
		"ACE_EarPlugs",
		"ACE_EntrenchingTool",
		"ACE_Fortify",
		"ACE_Flashlight_MX991",
		"ACE_IR_Strobe_Item",
		"ACE_Flashlight_XL50",
		"ACE_MapTools",
		"ACE_microDAGR",
		"ACE_SpraypaintBlack",
		"ACE_SpraypaintBlue",
		"ACE_SpraypaintGreen",
		"ACE_SpraypaintRed",
		"ACE_wirecutter",
		"ACRE_VHF30108SPIKE",
		"ACRE_VHF30108MAST",
		"ACE_Clacker",
		"ACE_EHP",
		"ACE_IR_Strobe_Item",
		"ACE_UAVBattery",
		"ACE_elasticBandage",
		"ACE_packingBandage",
		"ACE_quikclot",
		"ACE_bodyBag",
		"ACE_salineIV_250",
		"ACE_splint",
		"ACE_tourniquet"
	};
	items[] = {
		"U_O_CombatUniform_ocamo",
		"U_O_CombatUniform_oucamo",
		"U_O_V_Soldier_Viper_hex_F",
		"V_HarnessO_brn",
		"V_HarnessO_gry",
		"V_LegStrapBag_coyote_F",
		"H_HelmetO_ocamo",
		"H_HelmetO_oucamo",
		"H_HelmetO_ViperSP_hex_F",
		"H_HelmetHeavy_Hex_RF",
		"H_HelmetHeavy_Simple_Hex_RF",
		"H_HelmetHeavy_VisorUp_Hex_RF",
		"H_HelmetO_ocamo_sb_hex_RF",
		"lxWS_H_bmask_hex",
		"H_turban_02_mask_hex_lxws",
		"H_HelmetCrew_O",
		"H_HelmetLeaderO_ocamo",
		"H_HelmetLeaderO_oucamo",
		"H_HelmetSpecO_ocamo",
		"H_HelmetSpecO_blk",
		"G_Bandanna_khk",
		"G_Bandanna_tan",
		"G_Lowprofile",
		"G_Combat_lxWS",
		"G_Balaclava_snd_lxWS",
		"G_Balaclava_blk_lxWS",
		"ACE_NVG_Gen4_Black_WP",
		"ACE_NVG_Gen4_WP",
		"O_NVGoggles_hex_F",
		"Binocular",
		"ACE_Vector",
		"Laserdesignator_02",
		"ACE_MX2A",
		"Rangefinder",
		"Laserbatteries",
		"ItemMap",
		"O_UavTerminal",
		"ItemCompass",
		"ACE_Altimeter",
		"optic_r1_high_arid_lxWS",
		"optic_r1_high_lxWS",
		"optic_r1_high_black_sand_lxWS",
		"optic_r1_high_khaki_lxWS",
		"optic_r1_high_sand_lxWS",
		"optic_r1_low_arid_lxWS",
		"optic_r1_low_lxWS",
		"optic_r1_low_sand_lxWS",
		"optic_ACO_grn",
		"optic_Aco",
		"optic_Arco_blk_F",
		"optic_Arco_hex_lxWS",
		"optic_Arco",
		"optic_Holosight_arid_F",
		"optic_Holosight_blk_F",
		"optic_Holosight",
		"optic_MRCO",
		"optic_VRCO_RF",
		"optic_VRCO_tan_RF",
		"ACE_DBAL_A3_Green",
		"ACE_DBAL_A3_Red",
		"ACE_acc_pointer_green",
		"acc_pointer_IR",
		"ef_snds_mxar",
		"ef_snds_mxar_coy",
		"muzzle_snds_65_TI_blk_F",
		"muzzle_snds_65_TI_hex_F",
		"suppressor_m_lxWS",
		"suppressor_m_arid_lxWS",
		"suppressor_65_black_RF",
		"suppressor_65_sand_RF",
		"bipod_02_F_blk"

	};
	backpacks[] = {
		"B_Carryall_ocamo",
		"B_AssaultPack_ocamo",
		"B_FieldPack_ocamo",
		"B_ViperHarness_hex_F",
		"B_ViperLightHarness_hex_F",
		"O_shield_backpack_lxWS",
		"B_Carryall_oucamo",
		"B_FieldPack_oucamo",
		"B_LegStrapBag_coyote_F"
	};
};